[workspace]
members = [
    "wundergraph",
    "wundergraph_derive",
    "wundergraph_example",
    "wundergraph_cli",
    "wundergraph_bench",
]

[patch.crates-io]
#wundergraph_derive = { path = "wundergraph_derive"}
