# Based on https://github.com/actions-rs/meta/blob/master/recipes/quickstart.md
#
# While our "example" application has the platform-specific code,
# for simplicity we are compiling and testing everything on the Ubuntu environment only.
# For multi-OS testing see the `cross.yml` workflow.

on: [pull_request]

name: Quickstart

jobs:
  check_and_test:
    name: Check
    strategy:
      matrix:
        rust: ["1.38.0", "stable", "beta", "nightly"]
        backend: ["postgres", "sqlite"]
        os: [ubuntu-18.04, macos-latest, windows-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - name: Checkout sources
        uses: actions/checkout@v1

      - name: Install libpq (Linux)
        if: runner.os == 'Linux' && matrix.backend == 'postgres'
        run: |
          sudo apt-get update &&
          sudo apt-get install -y libpq-dev postgresql &&
          echo "host    all             all             127.0.0.1/32            md5" > sudo tee -a /etc/postgresql/9.5/main/pg_hba.conf &&
          sudo service postgresql restart && sleep 3 &&
          sudo -u postgres psql -c "ALTER USER postgres PASSWORD 'postgres';" &&
          sudo service postgresql restart && sleep 3

      - name: Install sqlite (Linux)
        if: runner.os == 'Linux' && matrix.backend == 'sqlite'
        run: sudo apt-get update && sudo apt-get install -y libsqlite3-dev sqlite3

      - name: Install libpq (MacOs)
        if: runner.os == 'macOS' && matrix.backend == 'postgres'
        run: |
          brew update &&
          brew install postgres &&
          /usr/local/opt/postgres/bin/pg_ctl -D /usr/local/var/postgres start &&
          sleep 3 &&
          /usr/local/opt/postgres/bin/createuser -s postgres

      - name: Install sqlite (MacOS)
        if: runner.os == 'macOS' && matrix.backend == 'sqlite'
        run: |
          brew update &&
          brew install sqlite

      - name: Install sqlite (Windows)
        if: runner.os == 'Windows' && matrix.backend == 'sqlite'
        shell: bash
        run: |
          choco install sqlite

      - name: Install libpq (Windows)
        if: runner.os == 'Windows' && matrix.backend == 'postgres'
        run: |
          choco install postgresql10 --force --params '/Password:password'

      - name: Install rust toolchain
        uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: ${{ matrix.rust }}
          override: true

      - name: Run cargo check for wundergraph_derive
        uses: actions-rs/cargo@v1
        with:
          command: check
          args: --manifest-path wundergraph_derive/Cargo.toml --features "${{ matrix.backend }}"

      - name: Run cargo check for wundergraph
        uses: actions-rs/cargo@v1
        with:
          command: check
          args: --manifest-path wundergraph/Cargo.toml --features "${{ matrix.backend }}"

      - name: Run cargo check for wundergraph_example
        uses: actions-rs/cargo@v1
        with:
          command: check
          args: --manifest-path wundergraph_example/Cargo.toml --features "${{ matrix.backend }}" --no-default-features

      - name: Run cargo check for wundergraph_bench
        uses: actions-rs/cargo@v1
        with:
          command: check
          args: --manifest-path wundergraph_bench/Cargo.toml --features "${{ matrix.backend }}" --no-default-features

      - name: Run cargo check for wundergraph_cli
        uses: actions-rs/cargo@v1
        with:
          command: check
          args: --manifest-path wundergraph_cli/Cargo.toml --features "${{ matrix.backend }}" --no-default-features

      - name: Run cargo test for wundergraph
        uses: actions-rs/cargo@v1
        with:
          command: test
          args: --manifest-path wundergraph/Cargo.toml --features "${{ matrix.backend }}" --no-default-features

      - name: Run test check for wundergraph_cli
        uses: actions-rs/cargo@v1
        with:
          command: test
          args: --manifest-path wundergraph_cli/Cargo.toml --features "${{ matrix.backend }}" --no-default-features

  clippy_check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: actions-rs/toolchain@v1
        with:
            toolchain: 1.38.0
            components: clippy
            override: true
      - uses: actions-rs/clippy-check@v1
        name: Clippy wundergraph_derive
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          args: --manifest-path wundergraph_derive/Cargo.toml --features "postgres sqlite"
      - uses: actions-rs/clippy-check@v1
        name: Clippy wundergraph
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          args: --manifest-path wundergraph/Cargo.toml --features "postgres sqlite"
      - uses: actions-rs/clippy-check@v1
        name: Clippy wundergraph_cli
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          args: --manifest-path wundergraph_cli/Cargo.toml --features "postgres sqlite"
